#!/bin/bash

python3 -m venv venv

. venv/bin/activate

pip install nbconvert

rm Markdowns/*

for file in $(ls Exercise_*/*.ipynb); do
    jupyter nbconvert --output-dir Markdowns --to markdown $file
done

