gitGraph
   commit id: "Initial commit"
   commit id: "Add schedules"
   branch feature
   commit id: "Add keynote to day 1"
   commit id: "Add excursion to day 2"
   commit id: "Extend the coffee break"
   checkout main
   cherry-pick id: "Extend the coffee break"
